#!/usr/bin/env bash

set -eu
set -o pipefail

if [ -e $HOME/.nodenv ]; then
  echo You have already installed nodenv!
  exit 0
fi

git clone https://github.com/nodenv/nodenv $HOME/.nodenv
cd $HOME/.nodenv && src/configure && make -C src

mkdir -p $HOME/.nodenv/plugins
git clone https://github.com/nodenv/node-build.git $HOME/.nodenv/plugins/node-build

NODE_VERSION=$(nodenv install --list | grep ^24 | tail -n 1)
nodenv install $NODE_VERSION
nodenv global $NODE_VERSION

npm install -g neovim
