#!/usr/bin/env bash

set -eu
set -o pipefail

if [ -e $HOME/.rbenv ]; then
  echo You have already installed rbenv!
  exit 0
fi

git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv
cd $HOME/.rbenv && src/configure && make -C src
mkdir -p $HOME/.rbenv/plugins
git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build

gem install refe2
bitclust setup
