#!/usr/bin/env bash

set -eu
set -o pipefail

if [ -e $HOME/.rbenv ]; then
  echo You have already installed rbenv!
  exit 0
fi

git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv
cd $HOME/.rbenv && src/configure && make -C src
mkdir -p $HOME/.rbenv/plugins
git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build
git clone https://github.com/rbenv/rbenv-default-gems.git $HOME/.rbenv/plugins/rbenv-default-gems

cat <<-EOL > $HOME/.rbenv/default-gem
dip
ruby-lsp
ruby-lsp-rails
refe2
neovim
EOL

# gem install mysql2 -v '0.5.6' -- --with-opt-dir=$(brew --prefix openssl) --with-ldflags=-L/opt/homebrew/opt/zstd/lib
bitclust setup
