#!/usr/bin/env bash

set -eu
set -o pipefail

if type "cargo" > /dev/null 2>&1; then
  echo You have already installed Rust!
  exit 0
fi

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
