#!/usr/bin/env bash

set -eu
set -o pipefail

mkdir $HOME/.config/nvim/
ln -sf $HOME/.vimrc $HOME/.config/nvim/init.vim

if [ -e $HOME/.vim/autoload/plug.vim ]; then
  echo You have already installed vim-plug!
else
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

$HOME/dotfiles/bin/build_vim
$HOME/dotfiles/bin/build_nvim
