# name: Build test

# on:
#   push:
#     branches:
#       - master
#   pull_request:

# jobs:
#   ubuntu:
#     runs-on: ubuntu-latest
#     container: ubuntu:latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Install required packages
#         run: apt-get update && apt-get install -y git sudo curl
#       - name: Install dotfiles
#         run: bin/setup
#   osx:
#     runs-on: macos-10.15
#     steps:
#       - uses: actions/checkout@v1
#       - name: Install dotfiles
#         run: bin/setup
